<a href="https://colab.research.google.com/github/gowdpa/Unemployment-and-Violence-by-Region/blob/main/Gowdy_Feeder_3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Overview
During this process, you will use Python to create a data subset of a larger data set

This is designed for someone with little to no experience with Python.

The overall process will proceed as follows:

1. Import necessary packages
2. Read in a .csv file to create a dataframe
3. Filter to create a subset of that dataframe that only contains relevant information
3. Export new subset as another .csv

#### Filtering a Data Set

This code will filter a data set named `"CountyHealthData_2014-2015.csv"`

This code will filter down the large data from the County Health Data set into a smaller data set that will let us analyze the correlation between Unemployment and Violent Crime by Region.

Begin by importing the pandas package using the following command:

You should download the csv file `"CountyHealthData_2014-2015.csv"` to follow along, or you can repeat these steps with your own data, saved as a csv file.
To import a .csv file to make it workable, follow these steps:
1. Click on the 5th icon down in CoLab, it should look like a folder.
2. There will be a row of icons under the word "Files." Click the icon that looks like a paper with a folded down corner and contains the up arrow.
3. Your computer files should pop up. Find where your data set is stored on your computer. Click on the data set, then click "open." This will being the data set into CoLAb to make it workable. It will take a second for the data set to upload, be patient.

NOTE: make sure that your csv file is saved in the same working directory as your .ipynb notebook file that you will use.


To read the dataframe object, we'll define our object df by executing the `pd.read_csv()` function on our data file by inserting the relative data file's name into the parathenses. To define the data frame, you will type the name that you will use in your code, and set it equal to the `pd.read_csv()` function.


To now use your data set to run the any functions, use the following command:

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("CountyHealthData_2014-2015.csv")

To start, we will explore the dataframe by looking at some basic attributes. These attributes contain values that provide helpful information about the dataframe, that guide our interaction with the dataframe.

Using pandas, we access attributes with the following syntax:

`<DataFrame name>.<attribute name>`

The `.shape` attribute is used to determine how many rows and columns (in that order) are available.

The `.size` attribute is used to show the number of cells in the dataframe (rows * columns).

The `.columns` attribute provides the column names for the dataframe

In [5]:
df.shape

(6109, 64)

In [6]:
df.size

390976

In [7]:
df.columns

Index(['State', 'Region', 'Division', 'County', 'FIPS', 'GEOID', 'SMS Region',
       'Year', 'Premature death', 'Poor or fair health',
       'Poor physical health days', 'Poor mental health days',
       'Low birthweight', 'Adult smoking', 'Adult obesity',
       'Food environment index', 'Physical inactivity',
       'Access to exercise opportunities', 'Excessive drinking',
       'Alcohol-impaired driving deaths', 'Sexually transmitted infections',
       'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists',
       'Mental health providers', 'Preventable hospital stays',
       'Diabetic screening', 'Mammography screening', 'High school graduation',
       'Some college', 'Unemployment', 'Children in poverty',
       'Income inequality', 'Children in single-parent households',
       'Social associations', 'Violent crime', 'Injury deaths',
       'Air pollution - particulate matter', 'Drinking water violations',
       'Severe housing problems', 'Driving alone to work',
       'Long commute - driving alone', '2011 population estimate',
       'Population that is not proficient in English',
       'Population living in a rural area', 'Diabetes', 'HIV prevalence rate',
       'Premature age-adjusted mortality', 'Infant mortality',
       'Child mortality', 'Food insecurity', 'Limited access to healthy foods',
       'Motor vehicle crash deaths', 'Drug poisoning deaths',
       'Uninsured adults', 'Uninsured children', 'Health care costs',
       'Could not see doctor due to cost', 'Other primary care providers',
       'Median household income', 'Children eligible for free lunch',
       'Homicide rate', 'Inadequate social support'],
      dtype='object')

` .value_counts()` is one of the most useful methods for categorical variables, as it  provides a frequency table.

In [8]:
df.Region.value_counts()

South        2803
Midwest      2038
West          834
Northeast     434
Name: Region, dtype: int64

Often you will want to select certain rows, columns, or specific cells from a large dataframe. This can be accomplished using indexing. There are some limitations, however.

For example, we can use numbers in square brackets to select certain rows, but doing so always returns all the columns in our dataset, such as the function: `df [0:3]`

If we use the `.iloc` attribute before our brackets, pandas accepts two numbers separated by a comma. The first number is for rows and the second for columns. This will give us the information of a specefic cell, as shown in the following function:

In [9]:
df.iloc[2,3]

'Anchorage Borough'

We can also select information for specific columns using the column names, however, you MUST type out the column name, and you cannot use the column number.

The dataset can also be filtered by using logical conditions (based on true or false), these can be added using nested square brackets.

See the example below.

- The inner statement, `df["State"]=="RI"` looks for a column name and checks if it equals `"RI"`
- The outer statement `df[ ... ]` uses the resulting column of `True/False` values to select rows
- When combined, these two commands call all of the data contained in rows where the value of the `State` field is equal to `"RI"`

In [10]:
df[df["State"] == "RI"]

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
4505,RI,Northeast,New England,Bristol County,44001,44001,Region 12,1/1/2014,4543.0,0.087,...,12.35,0.113,0.027,8579.0,0.077,18.0,64572,0.139,NaN,0.197
4506,RI,Northeast,New England,Bristol County,44001,44001,Region 12,1/1/2015,3891.0,0.087,...,11.67,0.110,0.044,8355.0,0.077,16.0,68415,0.155,NaN,NaN
4507,RI,Northeast,New England,Kent County,44003,44003,Region 12,1/1/2014,6313.0,0.122,...,15.55,0.110,0.027,9890.0,0.105,61.0,59682,0.223,1.44,0.187
4508,RI,Northeast,New England,Kent County,44003,44003,Region 12,1/1/2015,6458.0,0.122,...,18.94,0.114,0.046,9621.0,0.105,68.0,63232,0.230,1.30,NaN
4509,RI,Northeast,New England,Newport County,44005,44005,Region 12,1/1/2014,4457.0,0.109,...,12.29,0.119,0.033,8897.0,0.090,30.0,63434,0.222,NaN,0.176
4510,RI,Northeast,New England,Newport County,44005,44005,Region 12,1/1/2015,4730.0,0.109,...,10.33,0.118,0.048,8149.0,0.090,33.0,67291,0.230,NaN,NaN
4511,RI,Northeast,New England,Providence County,44007,44007,Region 12,1/1/2014,6468.0,0.154,...,15.67,0.190,0.049,9480.0,0.125,88.0,47601,0.484,4.10,0.229
4512,RI,Northeast,New England,Providence County,44007,44007,Region 12,1/1/2015,6124.0,0.154,...,17.51,0.182,0.058,8983.0,0.125,93.0,47642,0.487,3.70,NaN
4513,RI,Northeast,New England,Washington County,44009,44009,Region 12,1/1/2014,4961.0,0.092,...,10.56,0.105,0.031,8776.0,0.088,39.0,69150,0.172,NaN,0.157
4514,RI,Northeast,New England,Washington County,44009,44009,Region 12,1/1/2015,4939.0,0.092,...,13.18,0.107,0.047,8212.0,0.088,49.0,69267,0.177,NaN,NaN

To select multiple columns, it must be listed in its own nested set of square brackets.

See the examples below

In [11]:
df[["State","Region","Division","County","Unemployment"]]

     State Region  Division                      County  Unemployment
0       AK   West   Pacific  Aleutians West Census Area         0.091
1       AK   West   Pacific  Aleutians West Census Area         0.088
2       AK   West   Pacific           Anchorage Borough         0.054
3       AK   West   Pacific           Anchorage Borough         0.050
4       AK   West   Pacific          Bethel Census Area         0.152
...    ...    ...       ...                         ...           ...
6104    WY   West  Mountain                Uinta County         0.047
6105    WY   West  Mountain             Washakie County         0.054
6106    WY   West  Mountain             Washakie County         0.050
6107    WY   West  Mountain               Weston County         0.051
6108    WY   West  Mountain               Weston County         0.043

[6109 rows x 5 columns]

In [12]:
df[["State","Region","Division","County","Unemployment","Violent crime"]]

,State,Region,Division,County,Unemployment,Violent crime
0,AK,West,Pacific,Aleutians West Census Area,0.091,322.06
1,AK,West,Pacific,Aleutians West Census Area,0.088,317.35
2,AK,West,Pacific,Anchorage Borough,0.054,840.06
3,AK,West,Pacific,Anchorage Borough,0.050,823.16
4,AK,West,Pacific,Bethel Census Area,0.152,NaN
...,...,...,...,...,...,...
6104,WY,West,Mountain,Uinta County,0.047,45.36
6105,WY,West,Mountain,Washakie County,0.054,67.97
6106,WY,West,Mountain,Washakie County,0.050,69.92
6107,WY,West,Mountain,Weston County,0.051,108.03
6108,WY,West,Mountain,Weston County,0.043,97.95

`.iloc` is used for intergers, whereas `.loc` is used for column names.

To index with loc, the function `df.loc[:,[...]]` is used. If specific rows were selected, those numbers would go where the semi colon is: `df.loc[0:3,[...]]`. The values inside of the second brackets are the column names. To recieve a random sample, `.sample(n=)` is added at the end of the function.

All together, the function should appear like this: `df.[:,[...]].sample(n=)`

In [13]:
df.loc[:,["State","Region","Division","County","Unemployment","Violent crime"]].sample(n=50)

,State,Region,Division,County,Unemployment,Violent crime
1809,KS,Midwest,West North Central,Graham County,0.031,90.08
5649,VA,South,South Atlantic,Roanoke County,0.052,145.51
111,AL,South,East South Central,Hale County,0.099,169.64
2729,MN,Midwest,West North Central,Stearns County,0.055,193.34
4493,PA,Northeast,Mid-Atlantic,Warren County,0.067,309.01
4087,OH,Midwest,East North Central,Montgomery County,0.080,420.53
2561,MI,Midwest,East North Central,Roscommon County,0.115,188.43
1898,KS,Midwest,West North Central,Rice County,0.039,125.18
877,GA,South,South Atlantic,Gordon County,0.091,339.24
6016,WV,South,South Atlantic,Monroe County,0.057,109.04
724,FL,South,South Atlantic,Santa Rosa County,0.077,157.81
5316,TX,South,West South Central,Swisher County,0.084,281.62
848,GA,South,South Atlantic,Echols County,0.071,147.57
3092,MS,South,East South Central,Oktibbeha County,0.086,181.11
1786,KS,Midwest,West North Central,Dickinson County,0.056,164.48
4142,OH,Midwest,East North Central,Wayne County,0.061,99.87
3499,ND,Midwest,West North Central,Mountrail County,0.016,110.75
4505,RI,Northeast,New England,Bristol County,0.089,81.58
2037,KY,South,East South Central,Hardin County,0.079,241.16
3836,NV,West,Mountain,Lyon County,0.148,222.86
2057,KY,South,East South Central,Jessamine County,0.071,191.44
5134,TX,South,West South Central,Hutchinson County,0.053,763.98
139,AL,South,East South Central,Marion County,0.079,225.98
3419,NC,South,South Atlantic,Tyrrell County,0.097,146.62
3078,MS,South,East South Central,Marion County,0.095,193.48
2009,KY,South,East South Central,Estill County,0.089,100.67
4362,OR,West,Pacific,Union County,0.082,157.45
2460,MI,Midwest,East North Central,Crawford County,0.107,289.37
5400,UT,West,Mountain,Grand County,0.075,227.93
5580,VA,South,South Atlantic,Louisa County,0.059,117.45
1384,IL,Midwest,East North Central,Clinton County,0.076,153.01
3170,MT,West,Mountain,Deer Lodge County,0.074,360.52
4356,OR,West,Pacific,Sherman County,0.073,37.89
6091,WY,West,Mountain,Park County,0.058,255.97
5112,TX,South,West South Central,Hemphill County,0.025,417.98
4838,TN,South,East South Central,Maury County,0.093,612.61
981,GA,South,South Atlantic,Pulaski County,0.096,399.96
4498,PA,Northeast,Mid-Atlantic,Wayne County,0.072,117.05
3518,ND,Midwest,West North Central,Sioux County,0.048,0.00
115,AL,South,East South Central,Houston County,0.062,442.19
6046,WV,South,South Atlantic,Tucker County,0.080,228.76
2055,KY,South,East South Central,Jefferson County,0.086,579.99
1587,IN,Midwest,East North Central,Crawford County,0.092,90.14
2363,MD,South,South Atlantic,Garrett County,0.075,207.07
1799,KS,Midwest,West North Central,Finney County,0.044,364.75
4089,OH,Midwest,East North Central,Morgan County,0.114,53.12
5984,WV,South,South Atlantic,Hardy County,0.069,297.29
2072,KY,South,East South Central,Lawrence County,0.109,50.10
5079,TX,South,West South Central,Gray County,0.048,545.88
1744,IN,Midwest,East North Central,Whitley County,0.079,45.53

In [14]:
df.loc[:,["State","Region","Division","Unemployment","Violent crime"]].sample(n=50)

     State     Region            Division  Unemployment  Violent crime
3048    MS      South  East South Central         0.097            NaN
4893    TN      South  East South Central         0.087         510.72
4633    SD    Midwest  West North Central         0.073           9.79
3645    NE    Midwest  West North Central         0.042          34.60
1255    IA    Midwest  West North Central         0.062         264.50
1406    IL    Midwest  East North Central         0.070         134.14
4526    SC      South      South Atlantic         0.126         813.80
2042    KY      South  East South Central         0.074         160.64
3786    NM       West            Mountain         0.087         626.75
1199    IA    Midwest  West North Central         0.048         240.65
4097    OH    Midwest  East North Central         0.100          46.64
3952    NY  Northeast        Mid-Atlantic         0.076         161.59
2028    KY      South  East South Central         0.092         146.09
86      AL      South  East South Central         0.072         357.87
1202    IA    Midwest  West North Central         0.067         352.90
1853    KS    Midwest  West North Central         0.040          95.84
1783    KS    Midwest  West North Central         0.038         175.90
5045    TX      South  West South Central         0.063         178.18
5616    VA      South      South Atlantic         0.068         154.46
5982    WV      South      South Atlantic         0.083          63.77
161     AL      South  East South Central         0.044         176.94
3463    ND    Midwest  West North Central         0.021            NaN
5188    TX      South  West South Central         0.039           0.00
4108    OH    Midwest  East North Central         0.076          82.63
695     FL      South      South Atlantic         0.071         629.33
5486    VA      South      South Atlantic         0.049         438.16
4327    OR       West             Pacific         0.123          67.12
1075    HI       West             Pacific         0.051         228.68
4135    OH    Midwest  East North Central         0.070         110.33
3975    OH    Midwest  East North Central         0.114          47.98
5317    TX      South  West South Central         0.066         451.84
5253    TX      South  West South Central         0.057         148.40
2157    KY      South  East South Central         0.080         186.94
2551    MI    Midwest  East North Central         0.102         290.66
5330    TX      South  West South Central         0.070         238.98
2098    KY      South  East South Central         0.116          72.30
4048    OH    Midwest  East North Central         0.047          44.56
3285    NC      South      South Atlantic         0.096         156.72
1971    KY      South  East South Central         0.083          55.49
2234    LA      South  West South Central         0.073          34.57
1207    IA    Midwest  West North Central         0.042          66.21
5544    VA      South      South Atlantic         0.041         171.76
5972    WV      South      South Atlantic         0.079         241.29
5845    WI    Midwest  East North Central         0.073         178.19
1151    IA    Midwest  West North Central         0.041          56.03
3654    NE    Midwest  West North Central         0.034         102.09
4330    OR       West             Pacific         0.108         272.41
5796    WA       West             Pacific         0.109         103.74
5257    TX      South  West South Central         0.049         374.28
1845    KS    Midwest  West North Central         0.087         290.95

In [15]:
df.loc[:,["State","Region","Unemployment","Violent crime"]].sample(n=300)

     State   Region  Unemployment  Violent crime
335     AZ     West         0.081         376.42
1971    KY    South         0.083          55.49
3993    OH  Midwest         0.076         119.11
5909    WI  Midwest         0.069         108.26
4050    OH  Midwest         0.102          41.17
...    ...      ...           ...            ...
5151    TX    South         0.063         315.61
1188    IA  Midwest         0.053         226.15
5693    VA    South         0.134         205.44
2223    LA    South         0.072         345.64
2760    MO  Midwest         0.054         397.88

[300 rows x 4 columns]

####Creating a New Dataframe
Now a new dataframe needs to be created for this data set. This will be useful to export this data.

To do this, name the data using the same process as initally, but instead  of using `pd.read_csv()`we will use the function that created our data set.

Set the name of your new dataframe (here I am using `UseableData`) equal to the function that created your data set.

In [16]:
UseableData=df.loc[:,["State","Region","Unemployment","Violent crime"]].sample(n=300).copy()

We can run `UseableData` to test that we did the previous step correctly.

In [17]:
UseableData

     State   Region  Unemployment  Violent crime
5410    UT     West         0.039          41.47
384     CA     West         0.094         399.61
591     CO     West         0.040          66.82
3090    MS    South         0.155            NaN
1166    IA  Midwest         0.044          13.75
...    ...      ...           ...            ...
3041    MS    South         0.142            NaN
4543    SC    South         0.115         753.71
1677    IN  Midwest         0.079            NaN
653     FL    South         0.076         688.94
2779    MO  Midwest         0.056         406.31

[300 rows x 4 columns]

#### Exporting to .csv file

In order to export the data to a csv, we can use the method `.to_csv()` - adding the filename and extension within the parentheses at the end.

For our filtered subset we would run: `UseableData_subset.to_csv("UseableData_subset.csv")` this will export a `.csv` file in our working directory.

By default, this `.csv` will include the row of indices that pandas created when we read the original file into our notebook using `.read_csv`.

To eliminate these, we can add `index=false` to our statement, which tells it not bring in those index numbers.

`UseableData_subset.to_csv("UseableData_subset.csv", index=False)`

In [18]:
UseableData.to_csv("UseableData_subset.csv", index=False)